## 00. Pytorch fundamentals

Resource notebook: www.learnpytorch.io/00_pytorch_fundamentals/

Github link: https://github.com/mrdbourke/pytorch-deep-learning

In [ ]:
#print("Learning Pytorch; will die")
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors-n dimensional matrixs

### creating Tensors

pytorch tensors are created via 'toch.tensor() - - -https://pytorch.org/docs/stable/tensors.html;

In [ ]:
#scalar
#torch.tensor for creating
scalar=torch.tensor(7)
print(scalar)

#vector
vector=torch.tensor([7,7])

print(vector)

#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
print(MATRIX)

tensor(7)
tensor([7, 7])
tensor([[ 7,  8],
        [ 9, 10]])


In [ ]:
print(scalar.ndim, scalar.shape)
print(vector.ndim, vector.shape)
print(MATRIX.ndim, MATRIX.shape)

0 torch.Size([])
1 torch.Size([2])
2 torch.Size([2, 2])


In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR, TENSOR.ndim, TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) 3 torch.Size([1, 3, 3])


###Random Tensors

Random Tensors are important as neural networks start with random numbers and adjust them to better represent the data.

'Start with random numbers->look at data-> update random numbers->look at data->update number

In [ ]:
#create random tensor size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

#create random tensor into similar shape to image tensor
random_image_tensor=torch.rand(size=(224,224,3)) #height, width, colour channels
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
zeros=torch.zeros(3,4)
random_tensor=torch.rand(3,4)
ones=torch.ones(3,4)
#zeros, random_tensor, zeros*random_tensor
#ones, ones*random_tensor

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0.1932, 0.3356, 0.6260, 0.9831],
         [0.1118, 0.5974, 0.5733, 0.8193],
         [0.8466, 0.0923, 0.1303, 0.0418]]))

###Creating a Range on Tesnors

In [ ]:
#using a torch.arange()-tensor([1, 3, 5, 7, 9])
arange=torch.arange(start=1,end=11,step=2)

#creatin tesnors like-tensor([0, 0, 0, 0, 0])
five_zeros=torch.zeros_like(input=arange)
five_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
#Float 32 tensor
#precision is measure of detail and quantity is expressed
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=torch.float32
                             ,device=None #"cpu" "gpu" "cuda" tensors need to be same device
                             , requires_grad=False) #track gradients of tensors
 #dtype none defaults to float32 dtype is datatype if tensor
 #
float_32_tensor.dtype

#or; to change type
float_16_tensor=float_32_tensor.type(torch.float16)
float_32_tensor.dtype, float_16_tensor

(torch.float32, tensor([3., 6., 9.], dtype=torch.float16))

In [ ]:
randomtens=float_16_tensor*float_32_tensor
#for details
print(randomtens)
print(f"Datattpe of tensor: {randomtens.dtype}")
print(f"Shape of tensor: {randomtens.shape}")
print(f"Device of tensor: {randomtens.device}")

tensor([ 9., 36., 81.])
Datattpe of tensor: torch.float32
Shape of tensor: torch.Size([3])
Device of tensor: cpu


###Manipulating Tensors (tensor operations)

operations include:
* Add
* Subtract
* Multiplication (element wise)
* Division
* Matrix multiplication

two rules matix multiplication need to satisfy:
1. **inner dimensions**:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work

2. resulting matrix has shape **outer dimensions**:
* `(2,3)@(3,2)-->(2,2)`

In [ ]:
tensor=torch.tensor([1,2,3])
tensor+ 10 #add 10 torch.add(tensor,10)
tensor*10 #mult torch.mul(tensor,10)
tensor -10 #sub
tensor/2 #division

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
##Matrix multiplication
#two main ways: element wise & Matrix multiplcation (dot product)
print(tensor,"*",tensor)
print(f"Equal: {tensor*tensor}")
#matrix multiplication
print(torch.matmul(tensor,tensor)) #1*1 + 2*2 + 3*3

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])
tensor(14)


In [ ]:
# Shapes for matrix multiplication
tensor_a=torch.tensor([[1,2]
                       ,[3,4]
                       ,[5,6]])

tensor_b=torch.tensor([[7,10]
                       ,[8,11]
                       ,[9,12]])

tensor_a.shape#(3,2)
tensor_b.shape#(3,2)

##can use transpose to switch shape and dimensions
tensor_b.T, tensor_b.T.shape
torch.mm(tensor_a,tensor_b.T)##torch.mm=torch.matmul
print(f"Original shapes: tensor_a= {tensor_a.shape}, tensor_b={tensor_b.shape}")
print(f"New shapes: tensor_a={tensor_a.shape} (same as above), tensor_b.T={tensor_b.T.shape}")
print(f"Multiply:{tensor_a.shape}@{tensor_b.T.shape} matching inner dimensions")
print("Output:\n")
output=torch.mm(tensor_a,tensor_b.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_a= torch.Size([3, 2]), tensor_b=torch.Size([3, 2])
New shapes: tensor_a=torch.Size([3, 2]) (same as above), tensor_b.T=torch.Size([2, 3])
Multiply:torch.Size([3, 2])@torch.Size([2, 3]) matching inner dimensions
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean sum, etc (tensor aggregation)

In [ ]:
x=torch.arange(0,100,10)
print(f"the min is {torch.min(x)}") #x.min.()
print(f"the max is {torch.max(x)}") #x.max()
#torch.mean requires data type float 32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
torch.sum(x), x.sum()

the min is 0
the max is 90


(tensor(450), tensor(450))

In [ ]:
##finding position min and max
print(x)
#returns index/position in tensor where min/max value occurs
x.argmin(), x.argmax()


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


(tensor(0), tensor(9))

## Rehaping, stacking, squeezing and unsqueezing tensors

* Reshaping-reshapes an input tensor to defined shape
* View- Return a view of an input tensor of certain shape to keep same memory
* Stacking- combine multpile tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - Removes all `1` dimensions from tensor
* Unsqueeze - add `1` dimnesion to a target tensor
* Permute - Return a view of the input with dimensions permuted/swapped in a certain way


In [ ]:
#
import torch
x=torch.arange(1,10,1)
x, x.shape
##add extra dimension
x_reshape=x.reshape(1,9)
x_reshape2=x.reshape(9,1)
#x_reshape, x_reshape.shape
#x_reshape2 #reshape parameters must be multiples of tensor
y=torch.arange(1,11,1)
y_reshape=y.reshape(2,5)
y_reshape2=y.reshape(5,2)
y_reshape, y_reshape2

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]))

In [ ]:
#change the view
z=x.view(1,9)
z, z.shape
#changing z changes x as a view of tensor shares memory of original input
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#Stack tensors
x_stacked=torch.stack([x,x,x,x],dim=0)
y_stack=torch.stack([y,y],dim=1)
#can also use vstack and h stack
y_stack

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
x_reshape.shape #--torch.Size([1, 9])
x_reshape.squeeze() #--tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]) as oppose to tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]
print(f"Previous Tensor: {x_reshape} with size {x_reshape.shape}")
print(f"With squeeze {x_reshape.squeeze()} with size {x_reshape.squeeze().shape}")

Previous Tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]) with size torch.Size([1, 9])
With squeeze tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]) with size torch.Size([9])


In [ ]:
#toch.unaqueeze-adds a single dimension to a target tesnor at a specified dim
print(f"Previous target: {x_reshape.squeeze()}")
print(f"Previous shapoe: {x_reshape.squeeze().shape}")
#add a dim
x_unsqueeze=x_reshape.squeeze().unsqueeze(dim=0)
print(f"\nNew target: {x_unsqueeze}")
print(f"New shapoe: {x_unsqueeze.shape}")
#on dimension 1 adds to 2nd or index 1 dim
x_unsqueeze2=x_reshape.squeeze().unsqueeze(dim=1)
print(f"\n Dim 1 target: {x_unsqueeze2}")
print(f"Dim 1 shapoe: {x_unsqueeze2.shape}")


Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shapoe: torch.Size([9])

New target: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shapoe: torch.Size([1, 9])

 Dim 1 target: tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
Dim 1 shapoe: torch.Size([9, 1])


In [ ]:
#torch.permute rearranges dimensions of a target tensor in specified order
x_org=torch.rand(224,224,3) #[hieght , widhth, colour_channels]
#Permute org tensor to rearrange axis (or dim)
x_permuted=x_org.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f" Previos shape {x_org.shape}")
print(f" New shape {x_permuted.shape}")
x_org[0,0,0]=7
x_org[0,0,0],x_permuted[0,0,0]

 Previos shape torch.Size([224, 224, 3])
 New shape torch.Size([3, 224, 224])


(tensor(7.), tensor(7.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
x=torch.arange(1,10,1).reshape(1,3,3)
x, x.shape
#index on new tensor
print(f"x[0]={x[0]}")
print(f"\nx[0,0]={x[0,0]}")
print(f"\nx[0,0,0]={x[0,0,0]}")
#: can be used to all
x[:,:,2]

x[0]=tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

x[0,0]=tensor([1, 2, 3])

x[0,0,0]=1


tensor([[3, 6, 9]])

##Pytorch tensors & NumPy

Numpy is a popular scientific python numerical computing torch.library

Pytorch has to interact with it

* Data in Numpy what in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tesnro->Numpy->torch.Tensor.numpy()

In [ ]:
import numpy as np
import torch
#default num,py datatype is float 64
array=np.arange(1,8)
tensor=torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#change value in array; doesn't affect tensor/don't share memory
array=array+1
array, tensor

(array([3, 4, 5, 6, 7, 8, 9]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#tensor to numpy array
tensor=torch.ones(7)
numpy_tens=tensor.numpy()
#default datatype of tensor is float 32
tensor, numpy_tens

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random from random)

In short how a neural network learns:

`start with random numbers->tensor operations->update random numbers to try and make them better representations of the data->again->again...`

To reduce randomness in neural networks and PyTorch comes **random seed**

Random seed flavours the randomness

In [ ]:
import torch

#Create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A==random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
##make random but reproducible-set random seed
RANDOM_SEED=77

torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
#must set random seed everytime if using manual seed
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[0.2919, 0.2857, 0.4021, 0.4645],
        [0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (faster computations)

GPUs = faster computations on numbers, CUDA +NVDIA hardware and PYTOrch

### 1. Getting a GPU

1. Easiest - use google Colab for free GPU (upgrade uptions)
2. Use your own GPU - takes a little but of setup and requires purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services alllow renting computers on the cloud and accesss them


https://pytorch.org/get-started/locally/

In [4]:
#!nvidia-smi

### 2. Check for GPU access for PyTorch

In [7]:
#check for GPU access w/ PyTorch
import torch
torch.cuda.is_available()

False

In [9]:
# Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device
#count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reason we want tensors/models on the GPU is for speed computations

In [11]:
# create tensor on CPU
tensor=torch.tensor([1,2,3])
#tensor not on GPU
print(tensor, tensor.device)
#move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [13]:
#if tensor on GPU, can't transform to Numpy
tensor_on_gpu.numpy()
#to fix GPU tensor with NumPy issue, can set it to GPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])